version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: ci
    labels: [dependencies]
  - package-ecosystem: pip
    directory: /
    # requirements.txt only sets minimum versions, raise them only when needed
    versioning-strategy: increase-if-necessary
    schedule:
      interval: monthly
    commit-message:
      prefix: build
    labels: [dependencies]
