blank_issues_enabled: true
contact_links:
  - name: ESPHome documentation
    url: https://esphome.io
    about: General questions about ESPHome components / Allgemeine Fragen zu ESPHome
  - name: Home Assistant community
    url: https://community.home-assistant.io
    about: General Home Assistant questions / Allgemeine Fragen zu Home Assistant
